# Generated by Django 5.2.1 on 2025-06-22 18:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(choices=[('Group', 'Group Stage'), ('Quarter', 'Quarter Final'), ('Semi', 'Semi Final'), ('Final', 'Final')], default='Group', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matches', to='core.group'),
        ),
    ]
